routes/web.php
<?php

//use POS\Models\Transactions;
//
//Route::get('test', function () {
//
////    $items = unserialize(file_get_contents('results.txt'));
////
////    return view('welcome')->with('lines', $items);
//
//    $headers = [
//        'invoice_id',
//        'invoice_line',
//        'sage_amount',
//        'pos_excl',
//        'pos_discount',
//        'pos_amount',
//        'difference',
//    ];
//
//    file_put_contents('results.csv', implode(',', $headers) . "\n");
//
//    $transactions = Transactions::join('invnum', 'transactions.invoice_id', '=', 'invnum.autoindex')
//        ->whereRaw('invnum.invtotincl <> transactions.amount and id > 54000')
//        ->select(['invoice_id', 'transaction_data'])
//        ->chunk(100, function ($result) {
//            $items = array_flatten($result->map(function ($item) { return $item->invoice_id;})->toArray());
//            $lines = DB::table('_btblInvoiceLines')
//                ->whereIn('iInvoiceId', $items)
//                ->get(['idInvoiceLines', 'iInvoiceId', 'iStockCodeID', 'fQuantityLineTotIncl'])
//                ->groupBy('iInvoiceId');
//
//            $result = $result->map(function ($item) {
//                $decoded = json_decode($item->transaction_data)->items;
//                $item->transaction_data = $decoded;
//
//                return $item;
//            })->toArray();
//
//            $unmatched = [];
//
//            foreach ($result as $res) {
//                $item = $lines->get($res['invoice_id'])->keyBy('iStockCodeID');
//
//                foreach ($res['transaction_data'] as $data) {
//                    $total = $data->quantity * $data->sellingPrice;
//                    $totalExl = $data->quantity * $data->fExclPrice;
//                    $sage = $item->get($data->StockLink);
//                    if (! $sage) {
//                        continue;
//                    }
//
//                    $diff = $sage->fQuantityLineTotIncl - $total;
//
//                    if ($diff) {
////                        $unmatched [] = [
////                            'invoice_id' => $res['invoice_id'],
////                            'invoice_line' => $sage->idInvoiceLines,
////                            'sage_amount' => $sage->fQuantityLineTotIncl,
////                            'pos_excl' => $totalExl,
////                            'pos_discount' => $data->discount,
////                            'pos_amount' => $total,
////                            'difference' => $diff
////                        ];
//                        $body = [
//                            $res['invoice_id'],
//                            $sage->idInvoiceLines,
//                            $sage->fQuantityLineTotIncl,
//                            $totalExl,
//                            $data->discount,
//                            $total,
//                            $diff
//                        ];
//                        file_put_contents('results.csv', implode(',', $body) . "\n", FILE_APPEND);
//                    }
//                }
//            }
//
////            $original = [];
////            if (is_file('results.txt')) {
////                $original = unserialize(file_get_contents('results.txt'));
////            }
////
////            file_put_contents('results.txt', serialize(array_merge($unmatched, $original)));
//        });
//
//
//    dd($transactions);
//});

Route::get('home', 'HomeController@home');

Route::group(['middleware' => ['auth', 'checkedIn']], function () {
    Route::get('/', function () {
        return redirect()->route('pos.index');
    });

    Route::post('pos/save', 'POSController@save');
    Route::post('pos/approval', 'POSController@approval');
    Route::resource('pos', 'POSController');
    Route::post('add-customer', 'POSController@addCustomer');
    Route::resource('petty-cash', 'PettyCashController');
    Route::resource('transactions', 'TransactionsController');
    Route::resource('receipts', 'ReceiptsController');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('pos/print/{id}', 'POSController@printReceipt');
    Route::get('admin-end-of-day', 'TransactionsController@getAdminEndDay')->name('admin.endofday');
    Route::get('admin-complete-end-of-day', 'TransactionsController@getAdminCompleteEndDay');
    Route::get('admin-log', 'TransactionsController@getLog')->name('admin.log');
    Route::post('admin-end-of-day', 'TransactionsController@adminEndDay');
    Route::post('admin-complete-end-of-day', 'TransactionsController@adminCompleteEndDay');
    Route::resource('check-in', 'CheckinController', ['except' => ['index', 'show']]);
    Route::resource('till', 'TillController', ['except' => ['index', 'show']]);
    Route::resource('roles', 'RolesController');
    Route::get('users/import', 'UsersController@import');
    Route::resource('users', 'UsersController');
    Route::resource('assignment', 'AssignmentController');
    Route::resource('clients', 'ClientsController');
    Route::resource('petty-types', 'PettyCashTypesController');
    Route::resource('inventory', 'InventoryController');
    Route::get('endday', 'TransactionsController@getEndDay');
    Route::post('endday/', 'TransactionsController@endDay');
    Route::resource('admin/transactions', 'AdminTransactionsController', ['as' => 'admin']);
    Route::resource('approvals', 'ApprovalController');
    Route::post('pos/process', 'POSController@process');
    Route::resource('settings', 'SettingController');
});

Auth::routes();

resources/views/session/checkin.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Check In</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('check-in.store') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
                            <label for="warehouse_id" class="col-md-4 control-label">Select Store</label>

                            <div class="col-md-6">
                                <select name="warehouse_id" id="warehouse_id" class="form-control" required>
                                @foreach($assignments as $assignment)
                                    <option value="{{ $assignment->warehouse_id }}">{{ $assignment->warehouse->Name }}</option>
                                @endforeach
                                </select>

                                @if ($errors->has('warehouse_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('warehouse_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary" onclick="localStorage.removeItem('sale');">
                                    Check In
                                </button>
                                <a href="{{ url('endday') }}"
                                   class="btn btn-success">End Of Day</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/session/checkout.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Check In</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('check-in.destroy', $selected->WhseLink) }}">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <div>
                            <h3>Manage Till: {{ ucwords(strtolower($selected->Name)) }}</h3>
                        </div>
                        <div class="form-group{{ $errors->has('opening_amount') ? ' has-error' : '' }}">
                            <label for="opening_amount" class="col-md-4 control-label">Closing Amount</label>

                            <div class="col-md-6">
                                <input id="opening_amount" type="number" min="0" class="form-control" name="opening_amount" required>

                                @if ($errors->has('opening_amount'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('opening_amount') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Close Till
                                </button>
                                <a class="btn btn-warning" href="{{ route('check-in.create') }}">Switch Store</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/session/endday.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">End Of Day Report</div>
                <div class="panel-body">
                    <form class="form-horizontal" target="_blank" role="form" method="POST" action="{{ url('endday') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('warehouse_id') ? ' has-error' : '' }}">
                            <label for="warehouse_id" class="col-md-4 control-label">Select Store</label>

                            <div class="col-md-6">
                                <select name="warehouse_id" id="warehouse_id" class="form-control" required>
                                @foreach($assignments as $assignment)
                                    <option value="{{ $assignment->warehouse_id }}">{{ $assignment->warehouse->Name }}</option>
                                @endforeach
                                </select>

                                @if ($errors->has('warehouse_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('warehouse_id') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Get Report
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/session/till.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Check In</div>
                <div class="panel-body">
                    <form class="form-horizontal" role="form" method="POST" action="{{ route('till.store') }}">
                        {{ csrf_field() }}
                        <input type="hidden" name="selected" value="{{ $selected }}">
                        <div class="form-group{{ $errors->has('opening_amount') ? ' has-error' : '' }}">
                            <label for="opening_amount" class="col-md-4 control-label">Opening Amount</label>

                            <div class="col-md-6">
                                <input id="opening_amount" type="number" min="0" class="form-control" name="opening_amount" required>

                                @if ($errors->has('opening_amount'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('opening_amount') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-primary">
                                    Open Till
                                </button>
                                <a href="{{ route('check-in.create') }}"
                                   class="btn btn-danger">Back</a>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection