routes/web.php
<?php

//use POS\Models\Transactions;
//
//Route::get('test', function () {
//
////    $items = unserialize(file_get_contents('results.txt'));
////
////    return view('welcome')->with('lines', $items);
//
//    $headers = [
//        'invoice_id',
//        'invoice_line',
//        'sage_amount',
//        'pos_excl',
//        'pos_discount',
//        'pos_amount',
//        'difference',
//    ];
//
//    file_put_contents('results.csv', implode(',', $headers) . "\n");
//
//    $transactions = Transactions::join('invnum', 'transactions.invoice_id', '=', 'invnum.autoindex')
//        ->whereRaw('invnum.invtotincl <> transactions.amount and id > 54000')
//        ->select(['invoice_id', 'transaction_data'])
//        ->chunk(100, function ($result) {
//            $items = array_flatten($result->map(function ($item) { return $item->invoice_id;})->toArray());
//            $lines = DB::table('_btblInvoiceLines')
//                ->whereIn('iInvoiceId', $items)
//                ->get(['idInvoiceLines', 'iInvoiceId', 'iStockCodeID', 'fQuantityLineTotIncl'])
//                ->groupBy('iInvoiceId');
//
//            $result = $result->map(function ($item) {
//                $decoded = json_decode($item->transaction_data)->items;
//                $item->transaction_data = $decoded;
//
//                return $item;
//            })->toArray();
//
//            $unmatched = [];
//
//            foreach ($result as $res) {
//                $item = $lines->get($res['invoice_id'])->keyBy('iStockCodeID');
//
//                foreach ($res['transaction_data'] as $data) {
//                    $total = $data->quantity * $data->sellingPrice;
//                    $totalExl = $data->quantity * $data->fExclPrice;
//                    $sage = $item->get($data->StockLink);
//                    if (! $sage) {
//                        continue;
//                    }
//
//                    $diff = $sage->fQuantityLineTotIncl - $total;
//
//                    if ($diff) {
////                        $unmatched [] = [
////                            'invoice_id' => $res['invoice_id'],
////                            'invoice_line' => $sage->idInvoiceLines,
////                            'sage_amount' => $sage->fQuantityLineTotIncl,
////                            'pos_excl' => $totalExl,
////                            'pos_discount' => $data->discount,
////                            'pos_amount' => $total,
////                            'difference' => $diff
////                        ];
//                        $body = [
//                            $res['invoice_id'],
//                            $sage->idInvoiceLines,
//                            $sage->fQuantityLineTotIncl,
//                            $totalExl,
//                            $data->discount,
//                            $total,
//                            $diff
//                        ];
//                        file_put_contents('results.csv', implode(',', $body) . "\n", FILE_APPEND);
//                    }
//                }
//            }
//
////            $original = [];
////            if (is_file('results.txt')) {
////                $original = unserialize(file_get_contents('results.txt'));
////            }
////
////            file_put_contents('results.txt', serialize(array_merge($unmatched, $original)));
//        });
//
//
//    dd($transactions);
//});

Route::get('home', 'HomeController@home');

Route::group(['middleware' => ['auth', 'checkedIn']], function () {
    Route::get('/', function () {
        return redirect()->route('pos.index');
    });

    Route::post('pos/save', 'POSController@save');
    Route::post('pos/approval', 'POSController@approval');
    Route::resource('pos', 'POSController');
    Route::post('add-customer', 'POSController@addCustomer');
    Route::resource('petty-cash', 'PettyCashController');
    Route::resource('transactions', 'TransactionsController');
    Route::resource('receipts', 'ReceiptsController');
});

Route::group(['middleware' => ['auth']], function () {
    Route::get('pos/print/{id}', 'POSController@printReceipt');
    Route::get('admin-end-of-day', 'TransactionsController@getAdminEndDay')->name('admin.endofday');
    Route::get('admin-complete-end-of-day', 'TransactionsController@getAdminCompleteEndDay');
    Route::get('admin-log', 'TransactionsController@getLog')->name('admin.log');
    Route::post('admin-end-of-day', 'TransactionsController@adminEndDay');
    Route::post('admin-complete-end-of-day', 'TransactionsController@adminCompleteEndDay');
    Route::resource('check-in', 'CheckinController', ['except' => ['index', 'show']]);
    Route::resource('till', 'TillController', ['except' => ['index', 'show']]);
    Route::resource('roles', 'RolesController');
    Route::get('users/import', 'UsersController@import');
    Route::resource('users', 'UsersController');
    Route::resource('assignment', 'AssignmentController');
    Route::resource('clients', 'ClientsController');
    Route::resource('petty-types', 'PettyCashTypesController');
    Route::resource('inventory', 'InventoryController');
    Route::get('endday', 'TransactionsController@getEndDay');
    Route::post('endday/', 'TransactionsController@endDay');
    Route::resource('admin/transactions', 'AdminTransactionsController', ['as' => 'admin']);
    Route::resource('approvals', 'ApprovalController');
    Route::post('pos/process', 'POSController@process');
    Route::resource('settings', 'SettingController');
});

Auth::routes();

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Flash;
use Illuminate\Http\Request;
use POS\Models\Setting;
use POS\Repositories\CacheRepository;

class SettingController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('settings.index')->withSettings(Setting::all());
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $settings = Setting::all();
        $data = $request->all();
        foreach ($settings as $setting) {
            if (! in_array($setting->name, array_keys($data))) {
                continue;
            }

            $setting->value = $data[$setting->name];
            $setting->save();
        }

        CacheRepository::cacheSettings();

        Flash::success('Settings', 'Successfully updated system settings.');

        return redirect()->route('settings.index');
    }
}

resources/views/settings/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        System Settings
                    </div>

                    <div class="panel-body">
                        <form action="{{ route('settings.store') }}" method="post">
                            {{ csrf_field() }}
                            @foreach($settings as $setting)
                                <div class="row" style="border-bottom: 1px solid #e5e5e5; margin-top: 5px;">
                                    <div class="col-sm-10">
                                        <strong>{{ $setting->title }}</strong>
                                        <p style="text-align: justify;">{{ $setting->description }}</p>
                                    </div>
                                    <div class="col-sm-2" style="padding-top: 5px;">
                                        @if($setting->value == 'amount' || $setting->value == 'percentage')
                                            <select class="form-control" name="{{ $setting->name }}" id="{{ $setting->name }}">
                                                <option value="amount"{{ $setting->value == 'amount' ? ' selected' : '' }}>Amount</option>
                                                <option value="percentage"{{ $setting->value == 'percentage' ? ' selected' : '' }}>Percentage</option>
                                            </select>
                                        @elseif(is_numeric($setting->value))
                                            <input type="number" min="0" class="form-control" name="{{ $setting->name }}" id="{{ $setting->name }}" value="{{ $setting->value }}">
                                        @elseif($setting->value == 'Yes' || $setting->value == 'No')
                                            <select class="form-control" name="{{ $setting->name }}" id="{{ $setting->name }}">
                                                <option value="Yes"{{ $setting->value == 'Yes' ? ' selected' : '' }}>Yes</option>
                                                <option value="No"{{ $setting->value == 'No' ? ' selected' : '' }}>No</option>
                                            </select>
                                        @endif
                                    </div>
                                </div>
                            @endforeach

                            <div class="row">
                                <br>
                                <br>
                                <div class="col-sm-12">
                                    <input type="submit" class="btn btn-success pull-right" value="Save Settings">
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection